### ISSUE TITLE
Issues with Installing via brew

### ISSUE THREAD

**Issue by dredhorse** [bwilczynski/sonos-cli#3]
Hi, just tried to install via brew on OSX 10.13.6.

Got the following error:

==> Pouring python-3.7.3.high_sierra.bottle.tar.gz
Error: An unexpected error occurred during the `brew link` step
The formula built, but is not symlinked into /usr/local
Permission denied @ dir_s_mkdir - /usr/local/Frameworks
Error: Permission denied @ dir_s_mkdir - /usr/local/Frameworks

Created directory manually, set rights, tried installing again:

==> Downloading https://files.pythonhosted.org/packages/37/db/89d6b043b22052109d
######################################################################## 100.0%
==> python3 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/
Last 15 lines from /Users/marcus/Library/Logs/Homebrew/sonos-cli/01.python3:
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/private/tmp/sonos-cli--homebrew-virtualenv-20190328-42692-1ryt9wf/target
--install-scripts=/private/tmp/sonos-cli--homebrew-virtualenv-20190328-42692-1ryt9wf/target/bin
--single-version-externally-managed
--record=installed.txt

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'setuptools'

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/bwilczynski/homebrew-tap/issues

**Comment by bwilczynski** [comment]
Hi, looks like the issue with your homebrew installation. Have you checked what `brew doctor` is telling you?

**Comment by dredhorse** [comment]
looks like the python install did work correctly, I did deinstall python3 and did run the install again. It now works.
